.github/workflows/generate-initial-checksums.yml
README-DEV.md
config/ci.json

In this PR:
* Updated `config/ci.json` schema to `2-0-0` and added global default `payu-version` `1.1.5`
* Update initial generate checksums to use `payu-version`
* Update `README-DEV.md` with `payu-version` and `python-version` usages.
Duplicated @CodeGat PR here for updating ACCESS-ESM1.5 configs repository ACCESS-NRI/access-esm1.5-configs#55
References ACCESS-NRI/model-config-tests#37

Add payu-version to config/ci.json and initial generate checksums workflow

---

.github/workflows/ci.yml

In this PR:
- Added `on.create` trigger from https://github.com/ACCESS-NRI/model-configs-template/commit/a1988f076af334d23da3e903b490e6a24f0421bf and https://github.com/ACCESS-NRI/model-configs-template/pull/3/commits/d6e6fdfd558d336aa579ae33d944efe406a18c8d (from ACCESS-NRI/model-configs-template#3)
NOTE: We only have to add this CI to `main` (and not other `dev-*`/`release-*` branches) because only future configurations (which are based on `ci.yml` from `main`) will require this feature. 
References ACCESS-NRI/model-config-tests#58

Add `on.create` Trigger

---

config/ci.json

In this PR:
* Update the version of the model-config-tests class to `0.0.8` (contains changes from ACCESS-NRI/model-config-tests#90)
* Update default QA tests to use the new `access_esm1p6` markers

ci.json: Updated model-config-tests to 0.0.8 and now uses access_esm1p6 test markers

---

atmosphere/cable.nml

Closes #18. This PR updates the `cable.nml` file to use Medlyn photosynthes, to be used for the summer simulations.

Update cable.nml to use Medlyn photosynthesis

---

config.yaml

Closes #32 
This PR increases the collation walltime to 1.5h to try and prevent occasional jobs where the walltime is exceeded.

Increase collation walltime to 1.5h

---

config.yaml

Closes AMIP half of #47. Updates the executables to `pr47-3`, which should be compatible with the updated cable namelists

Update UM to cable.nml compatible version

---

config.yaml
manifests/exe.yaml

Closes preindustrial half of #47. Updates the executables to `pr43-7`, which should be compatible with the recent changes to the cable namelist.

Update UM code to be compatible with new cable namelist

---

config.yaml
manifests/restart.yaml

Closes #39 
Adds the new LUH3 based restart as the default for the pre-industrial configuration.

Use LUH3 restart

---

atmosphere/cable.nml

Closes #53 
Switches on `l_luc` for the AMIP configuration, as required for the land use change to run.
Compared to the AMIP namelist for ESM1.5, differences are:
```diff
diff esm1p5cable cable.nml 
3,5d2
<  filename%veg     = 'INPUT/def_veg_params.txt'
<  filename%soil    = 'INPUT/def_soil_params.txt'
< !
8a6
>   cable_user%GS_SWITCH = 'medlyn' ! alternative is 'leuning' - used for ESM1.5
15c13
<   cable_user%FWSOIL_SWITCH = 'standard' ! Controls root water uptake function
---
>   cable_user%FWSOIL_SWITCH = 'Haverd2013' ! Controls root water uptake function
34a34,39
>   cable_user%access13roots = .TRUE. ! TRUE uses prescribed froot values
>                                     ! FALSE uses 'rootbeta' parameterisation (as ACCESS-CM2)
>   cable_user%L_REV_CORR = .TRUE.
>   snmin = 0.11
> …
```

Switch on LUC for AMIP run

---

config/ci.json

As we discussed in person, this PR reconfigures the CI to:
- run `reproducibility` checksum and checksum_slow marks by default (meaning historical, restart and repeat repro tests are run)
- use payu dev
- use the latest `model-config-tests`
These settings should be revisited when we are ready to release a config.

Add checksum_slow to default repro checks

---

config.yaml
ocean/diagnostic_profiles/diag_table_detailed
ocean/diagnostic_profiles/diag_table_standard
ocean/diagnostic_profiles/diag_table_wombatlite
ocean/input.nml

Work related to #41.
Collation failures form the majority of post-processing problems which have recently caused problems during esm.6 development. Based on discussions, the preference is to remove the collation step entirely by writing complete ocean output files during the model run. 
This pull request sets the ocean `io_layout=1,1` and switches off the collation step. Additionally, compression is enabled for the MOM output with `deflate=4` to maintain similar output sizes as before. 
Adding an `io_layout` requires us to remove  the basin specific flux variables. Including these with an `io_layout` can either cause the model to crash, or silently write wrong output. See [here](https://github.com/ACCESS-NRI/access-esm1.6-configs/issues/51) for details.
This change impacts the model …

Remove ocean output collation

---

config.yaml
manifests/exe.yaml

Closes #69.
This updates the `dev-amip` configuration executables to match the `dev-preindustrial+concentrations` branch, in particular bringing in a fix which makes the UM deterministic.

Update amip exe for determinism fix

---

.github/workflows/generate-initial-checksums.yml

Closes #73
A later workflow is requiring `checks: write` but we didn't give that permission initially. Now we do.
* Give the repro-ci job `permissions.checks: write`

Add `checks: write` Permission to Generate Initial Checksums

---

.github/workflows/generate-initial-checksums.yml

Following on from this PR: https://github.com/ACCESS-NRI/access-esm1.6-configs/pull/75, this PR updates the branch of the `generate-checksums` workflow in `model-config-tests` to `main`. The branch `146-add-marker-input-for-initial-checksums` has now been merged in https://github.com/ACCESS-NRI/model-config-tests/pull/147

generate-initial-checksums: Update workflow version

---

atmosphere/input_atm.nml

Update `input_atm.nml` with new solar constant.
See #82 and https://github.com/ACCESS-Community-Hub/access-esm1.6-dev-experiments/issues/7

Use the CMIP7 pre-industrial solar constant

---

config.yaml
manifests/restart.yaml

Closes #86.
This PR points the `dev-preindustrial+concentrations` configuration to the new restart for the next spinup simulation. 
The new restart is located at `/g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.04.08`, and has been created as follows:
1. The `ocean`, `ice`, and `coupler` directories were copied from `/scratch/p66/pjb581/access-esm/archive/pi_concentrations_test3-restart-840-35bbe5a7/backup_restart061`. My understanding is that this restart comes from the long ocean spinup, and the bgc restart `/ocean/ocean_wombatlite.res.nc` has been altered with deep tracer values reset to the original values from `/g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2024.12.10/ocean/ocean_wombatlite.res.n …

Use new combined restart file

---

ocean/diagnostic_profiles/source_yaml_files/diag_table_detailed_source.yaml
ocean/diagnostic_profiles/source_yaml_files/diag_table_standard_source.yaml
ocean/diagnostic_profiles/source_yaml_files/diag_table_wombatlite_source.yaml

Closes #95.
Removes 1D ocean variables from the `diag_table_..._source.yaml` files so that their content matches the variables in the actual `diag_tables`.

Remove 1D variables from source yaml files

---

ocean/diagnostic_profiles/diag_table_wombatlite
ocean/diagnostic_profiles/source_yaml_files/diag_table_wombatlite_source.yaml

Closes #93 
This PR updates the wombatlite diag table with several scalar wombatlite variables. 
Note: I've also removed the 1D flux fields from the `diag_table_wombatlite_source.yaml` file as these variables [cause bugs](https://github.com/ACCESS-NRI/access-esm1.6-configs/issues/51). I'd previously removed these variables from the actual diag_tables, but forgot to remove them from the source yaml files

93 update wombatlite diags

---

atmosphere/cable.nml
config.yaml
manifests/exe.yaml
manifests/input.yaml
manifests/restart.yaml

Closes preindustrial half of #109 (AMIP changes to follow).
This PR points the configuration to the updated phenology file, allowing the number of phenology types to be read from the file rather than hardcoded. 
Also includes changes to input manifests which were skipped in #131.

Update phenology file

---

atmosphere/cable.nml
config.yaml
manifests/exe.yaml
manifests/input.yaml

Closes the AMIP half of #109. See #133 for the PI config changes.

Update AMIP config phenology file
